### ISSUE TITLE
FYI: ewoc

### ISSUE THREAD

**Issue by alphapapa** [john2x/dank-mode#1]
Hi,

This looks cool.  FYI, Emacs has a built-in UI library, `ewoc`, that might be useful to you.  I use it in Ement.el, and it simplifies many things.  @publicimageltd recently rewrote his [lister](https://github.com/publicimageltd/lister) package when I showed it to him.  :)

**Comment by john2x** [comment]
Damn I wish I knew about that. I'll have to try it out, that looks perfect. Thanks!

**Comment by alphapapa** [comment]
:)  You can see some more examples of it in the `vc-dir` library (which I recently discovered, too).

**Comment by john2x** [comment]
Started using `ewoc` in #2. Really great so far and is simplifying a lot of things :tada:

**Comment by alphapapa** [comment]
Cool!  Here are some functions you might find useful.  I might propose them as a patch to EWOC sometime:

https://github.com/alphapapa/ement.el/blob/3c14f6c4c10f994218689d372bf1fdbe714ac529/ement-room.el#L2130

BTW, if you're brave enough, you might try using embedded EWOCs (i.e. EWOCs within EWOCs) for nesting.  According to the EWOC Info manual, that does work.  :)

**Comment by john2x** [comment]
Awesome, thanks! Yeah I was missing some functions, especially the search by predicate ones. Do you mind if I copy those over?

I was wondering if nesting was possible. But I ended up reworking  how the comment tree was parsed and ended up with a structure that could be easily `flatten-tree`'d, which I think ended up being more simple.

One thing I wasn't sure though or if I was just holding it wrong, can there be multiple top-level EWOCs in a buffer? I was having trouble rendering 2 at the same time (rendering the 2nd one would overwrite the first one).

Thanks for the reviews btw! Wasn't expecting those.

**Comment by alphapapa** [comment]
> Awesome, thanks! Yeah I was missing some functions, especially the search by predicate ones. Do you mind if I copy those over?

Please do.  The code is GPL'ed, after all.  :)

> I was wondering if nesting was possible. But I ended up reworking how the comment tree was parsed and ended up with a structure that could be easily `flatten-tree`'d, which I think ended up being more simple.

Where is `flatten-tree` from?  I'm familiar with `-flatten` from Dash (and I wish Elisp had such a function built-in).

> One thing I wasn't sure though or if I was just holding it wrong, can there be multiple top-level EWOCs in a buffer? I was having trouble rendering 2 at the same time (rendering the 2nd one would overwrite the first one).

AFAIK, there can be more than one, because `ewoc-create` is:
```
(ewoc-create PRETTY-PRINTER &optional HEADER FOOTER NOSEP)

Create an empty ewoc.

The ewoc will be inserted in the current buffer at the current position.
```
But in Ement.el, I've only used one per-buffer, so far.

> Thanks for the reviews btw! Wasn't expecting those.

I'm happy to share what I've learned about EWOC, since it appears to be like a hidden gem in Emacs, and there seems to be much wheel-reinventing due to its not being well known.

Now, if we could improve `widget`'s documentation, we might unlock a whole new generation of Emacs GUIs.  :)

**Comment by alphapapa** [comment]
I just did a quick experiment with nested EWOCs, and it appears to be so simple, that I have to share this:
![taxy-ewoc](https://user-images.githubusercontent.com/601365/134794690-ab7318ce-d9a9-4e6e-a02b-3a9c441d3240.png)

**Comment by publicimageltd** [comment]
That does look easy indeed. Any of you guys interested in using Lister? It does have predicate searching, marking, etc., and all kind of stuff while still using Ewoc. But again @alphapapa makes me think I should have done something differently .. namely, `Lister` simulates sublists by indenting items; this might be done more elegantly with nested `Ewocs`... :thinking:

> Where is flatten-tree from? I'm familiar with -flatten from Dash (and I wish Elisp had such a function built-in).

`flatten-tree` is built-in (at least in 27.2).

**Comment by alphapapa** [comment]
> That does look easy indeed. Any of you guys interested in using Lister? It does have predicate searching, marking, etc., and all kind of stuff while still using Ewoc. But again @alphapapa makes me think I should have done something differently .. namely, `Lister` simulates sublists by indenting items; this might be done more elegantly with nested `Ewocs`... thinking

I'm not sure what the best solution is yet.  Ideally there would be a kind of 1:1 mapping between a hierarchy (like a Taxy struct) and an EWOC tree.  You can see my current WIP attempt here: https://github.com/alphapapa/taxy.el/blob/wip/ewoc/taxy-ewoc.el  I use the printer function to insert nested EWOCs in new nodes; it seems like an elegant hack, but it doesn't work quite perfectly, and I'm not sure how egregious a violation of purity it is.  :)  EWOC's documentation says that EWOCs can be nested, but AFAIK there's no example of how to do that, so I don't know how it's intended to be done.  Maybe I need to insert the EWOCs one at a time manually rather than a "cascading" insertion from inserting the root taxy node, but if I can get it to work this way, it would seem simpler and more elegant.

And maybe EWOC needs to be extended a bit to support nested EWOCs more naturally.  I don't know if that's necessary, or what it might entail, but it seems like it could be made more straightforward if it were explicitly supported.

Anyway, all that is off-topic here; sorry to John for using his repo for this.  :)  Feel free to talk about this on the Taxy repo if you're interested.

> 
> > Where is flatten-tree from? I'm familiar with -flatten from Dash (and I wish Elisp had such a function built-in).
> 
> `flatten-tree` is built-in (at least in 27.2).

Huh, somehow I overlooked that, after wanting it for years.  Thanks.

**Comment by publicimageltd** [comment]
> Huh, somehow I overlooked that, after wanting it for years. Thanks.

That's a recurring theme in my life with Emacs...

**Comment by john2x** [comment]
Nested EWOCs sound pretty good. I'll have to revisit that in the future. For now I'm pretty happy with #2. Cheers for the interesting discussion, learned a lot :)
